### ISSUE TITLE
Cannot run npx command to use with Cursor

### ISSUE THREAD

**Issue by 50bbx** [jerhadf/linear-mcp-server#6]
I am runnning `npx -y @modelcontextprotocol/server-linear` locally in order to see if the server starts. It doesn't:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@modelcontextprotocol%2fserver-linear - Not found
npm ERR! 404 
npm ERR! 404  '@modelcontextprotocol/server-linear@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

It says that the package could not be found.

Did you publish the package?

**Comment by harrisrobin** [comment]
I also tried it with a local setup and that did not work either:

![Image](https://github.com/user-attachments/assets/636ea538-7e91-46d2-b757-441f900e2901)

**Comment by kylian-p** [comment]
Same problem, even via Smithery's CLI: https://smithery.ai/server/linear-mcp-server

<img width="926" alt="Image" src="https://github.com/user-attachments/assets/184abb93-84b9-46ea-acaf-466faa79cf20" />

**Comment by smwitkowski** [comment]
#8 Should fix this

**Comment by jerhadf** [comment]
sorry for the delay here all - I've been out and haven't had the time to maintain this package recently. 

@smwitkowski thanks for the PR! approved and merged 

I published the package to NPM here and updated the Readme with the correct info: https://www.npmjs.com/package/linear-mcp-server

@kylian-p @50bbx @harrisrobin please use the updated Readme instructions! the correct installation command is `npx -y linear-mcp-server` or `npm i linear-mcp-server`

**Comment by jerhadf** [comment]
please let me know if anyone experiences issues with this, explain the problem and I'm happy to re-open the issue and look into it :)

**Comment by nk1tz** [comment]
`npx @smithery/cli install linear-mcp-server` works fine now

**Comment by 50bbx** [comment]
@jerhadf I went to https://www.npmjs.com/package/linear-mcp-server and here's what documentation says at the moment:

```json
{
  "mcpServers": {
    "linear": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-linear"
      ],
      "env": {
        "LINEAR_API_KEY": "your_linear_api_key_here"
      }
    }
  }
}
```

so the command should be `LINEAR_API_KEY=MY_API_KEY npx -y @modelcontextprotocol/server-linear`. This does not work.

```
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@modelcontextprotocol%2fserver-linear - Not found
npm error 404
npm error 404  '@modelcontextprotocol/server-linear@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /Users/leonardostenico/.npm/_logs/2025-02-21T09_01_30_434Z-debug-0.log
```

Then I also tried the `LINEAR_API_KEY=MY_API_KEY npx -y linear-mcp-server` you are suggesting, but it still does not work in Cursor. It works in the terminal, however:

<img width="287" alt="Image" src="https://github.com/user-attachments/assets/e165f04a-8b35-4b7f-a081-19c96010f963" />

So in the end I am really missing one final piece: why is it not working in cursor?
